"""
Database Schema — All table definitions for the QuantTrading system.
(This file defines the structure of every table in the PostgreSQL database)

PURPOSE:
    Defines all 7 database tables using SQLAlchemy ORM models.
    Each class maps to a PostgreSQL table, and each attribute maps to a column.
    When the bot starts, it calls Base.metadata.create_all() to ensure
    all tables exist (creates missing ones, doesn't touch existing ones).

TABLE OVERVIEW:
    1. users           — User authentication (email, password, PIN)
    2. bitcoin_prices   — Historical price snapshots (every 60 seconds per symbol)
    3. news_articles    — News headlines fetched for AI analysis
    4. trade_signals    — AI-generated BUY/SELL signals from FinBERT
    5. accounts         — User trading accounts (each has a balance and risk strategy)
    6. portfolio_assets — Current holdings (what the account "owns")
    7. trades           — Individual trade records (Long/Short with SL/TP)

DATA FLOW:
    news_articles → (FinBERT) → trade_signals → (3-Layer Verification) → trades
    accounts ←→ portfolio_assets ←→ trades
"""

from sqlalchemy import Column, Integer, String, Float, DateTime, Text, ForeignKey, Boolean
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime
from database import engine, SessionLocal, Base


# ═══════════════════════════════════════════════════════════════════════
#  TABLE 0: USERS
#  (Authentication table — stores login credentials)
#  
#  DETAILS:
#    - email: unique identifier, always stored lowercase
#    - hashed_password: bcrypt hash, never stores plaintext
#    - pin_hash: optional PIN for extra security (future feature)
#    - Google OAuth users have hashed_password = "GOOGLE_AUTH_ACCOUNT"
# ═══════════════════════════════════════════════════════════════════════
class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True)
    hashed_password = Column(String)
    pin_hash = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.now)


# ═══════════════════════════════════════════════════════════════════════
#  TABLE 1: PRICE SNAPSHOTS
#  (Historical price data for all tracked symbols)
#  
#  DETAILS:
#    - Stores one row per symbol per price check cycle (every ~60 seconds)
#    - Used by the frontend charts and the Markets Explorer page
#    - Named "bitcoin_prices" for legacy reasons but stores ALL symbols
#    - The bot_engine.py writes to this table during price_check_cycle()
# ═══════════════════════════════════════════════════════════════════════
class BitcoinPrice(Base):
    __tablename__ = "bitcoin_prices"
    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String, index=True)       # e.g., "BTC-USD", "AAPL", "GC=F"
    price = Column(Float)                     # Current price in USD
    timestamp = Column(DateTime, default=datetime.now)


# ═══════════════════════════════════════════════════════════════════════
#  TABLE 2: NEWS ARTICLES
#  (News headlines fetched from NewsAPI and RSS feeds)
#  
#  DETAILS:
#    - data_ingestion.py writes to this table when fetching news
#    - ai_analysis.py reads from this table to run FinBERT
#    - Articles are REPLACED (not appended) each cycle to keep data fresh
#    - sentiment_score is updated by ai_analysis.py after FinBERT processes it
#    - Old articles are cleared when new ones are fetched for the same symbol
# ═══════════════════════════════════════════════════════════════════════
class NewsArticle(Base):
    __tablename__ = "news_articles"
    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String, index=True)       # Which symbol this article relates to
    title = Column(String)                    # Headline text (fed to FinBERT)
    url = Column(String)                      # Link to original article
    sentiment_score = Column(Float)           # FinBERT score: -1.0 (bearish) to +1.0 (bullish)
    timestamp = Column(DateTime, default=datetime.now)


# ═══════════════════════════════════════════════════════════════════════
#  TABLE 3: AI TRADE SIGNALS
#  (Generated by FinBERT after analyzing news headlines)
#  
#  DETAILS:
#    - ai_analysis.py creates these after running FinBERT on news articles
#    - Only BUY and SELL signals are saved (NEUTRAL is discarded)
#    - The 'executed' flag tracks whether trade_executor.py has processed it
#    - trade_executor.py queries for executed=False signals every 5 minutes
#    - Once processed (whether a trade was placed or not), executed is set to True
#    - confidence is abs(compound_score) from FinBERT: higher = stronger conviction
# ═══════════════════════════════════════════════════════════════════════
class TradeSignal(Base):
    __tablename__ = "trade_signals"
    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String, index=True)       # Which symbol this signal is for
    signal = Column(String)                   # "BUY" or "SELL" (NEUTRAL is not saved)
    confidence = Column(Float)                # 0.0 to 1.0 — how sure the AI is
    reasoning = Column(Text)                  # Human-readable explanation of why
    executed = Column(Boolean, default=False)  # Has trade_executor.py processed this?
    timestamp = Column(DateTime, default=datetime.now)


# ═══════════════════════════════════════════════════════════════════════
#  TABLE 4: TRADING ACCOUNTS
#  (Each user can have multiple accounts with different risk strategies)
#  
#  DETAILS:
#    - balance: current available cash (decreases when trades are opened)
#    - initial_balance: starting balance (used to calculate overall return %)
#    - strategy: "Low", "Moderate", or "Aggressive" — controls risk profile
#    - The bot trades on ALL accounts simultaneously
#    - Each account's strategy determines position sizing, max trades, SL/TP levels
# ═══════════════════════════════════════════════════════════════════════
class Account(Base):
    __tablename__ = "accounts"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    name = Column(String, index=True)         # Display name (e.g., "High Risk Portfolio")
    balance = Column(Float)                   # Current available cash
    initial_balance = Column(Float)           # Starting balance (for return % calculation)
    strategy = Column(String)                 # "Low", "Moderate", or "Aggressive"
    asset_types = Column(Text, nullable=True) # JSON array: ["Stocks", "Crypto", "Forex"]
    sectors = Column(Text, nullable=True)     # JSON array: ["Technology", "Energy", ...]
    created_at = Column(DateTime, default=datetime.now)


# ═══════════════════════════════════════════════════════════════════════
#  TABLE 5: PORTFOLIO ASSETS
#  (What each account currently "holds" — their open positions aggregate)
#  
#  DETAILS:
#    - Created when a trade is first opened for a symbol on an account
#    - shares: total number of units held (e.g., 0.5 BTC, 10 AAPL shares)
#    - avg_price: weighted average entry price across all buys
#    - current_price: updated every 60 seconds by the position manager
#    - Deleted when shares reach 0 (all positions closed)
#    - This is the "portfolio view" — shows what the account owns at a glance
# ═══════════════════════════════════════════════════════════════════════
class PortfolioAsset(Base):
    __tablename__ = "portfolio_assets"
    id = Column(Integer, primary_key=True, index=True)
    account_id = Column(Integer, ForeignKey("accounts.id"))
    symbol = Column(String, index=True)       # e.g., "BTC-USD"
    asset_class = Column(String)              # "Crypto", "Stock", "Forex", "Commodity"
    shares = Column(Float)                    # Number of units held
    avg_price = Column(Float)                 # Weighted average entry price
    current_price = Column(Float, default=0.0)  # Live price (updated every 60s)


# ═══════════════════════════════════════════════════════════════════════
#  TABLE 6: INDIVIDUAL TRADES
#  (Every single trade the bot has ever made — the full trade ledger)
#  
#  DETAILS:
#    - trade_type: "Long" (buy low, sell high) or "Short" (sell high, buy low)
#    - status: "Open" (still active) or "Closed" (position exited)
#    - entry_price: price when the trade was opened
#    - current_price: live price (updated every 60s for open trades)
#    - quantity: number of shares/units (position_value / entry_price)
#    - position_value: total dollar amount invested in this trade
#    - stop_loss_price: auto-close if price hits this (limits losses)
#    - take_profit_price: auto-close if price hits this (locks in gains)
#    - pnl: profit/loss as a percentage
#    - pnl_dollars: profit/loss in actual dollar amount
#    - signal_id: which AI signal triggered this trade
#    - reasoning: full 3-layer verification report (shown in frontend)
#    - closed_at: timestamp when the trade was closed (null if still open)
# ═══════════════════════════════════════════════════════════════════════
class Trade(Base):
    __tablename__ = "trades"
    id = Column(Integer, primary_key=True, index=True)
    account_id = Column(Integer, ForeignKey("accounts.id"))
    symbol = Column(String, index=True)                  # e.g., "BTC-USD"
    trade_type = Column(String)                          # "Long" or "Short"
    status = Column(String, default="Open")              # "Open" or "Closed"
    entry_price = Column(Float)                          # Price when trade was opened
    current_price = Column(Float)                        # Live price (updated every 60s)
    quantity = Column(Float, default=0.0)                # Number of shares/units
    position_value = Column(Float, default=0.0)          # Total $ invested in trade
    stop_loss_price = Column(Float, nullable=True)       # Auto-close price for losses
    take_profit_price = Column(Float, nullable=True)     # Auto-close price for profits
    pnl = Column(Float, default=0.0)                     # Profit/loss percentage
    pnl_dollars = Column(Float, default=0.0)             # Profit/loss in dollars
    signal_id = Column(Integer, nullable=True)           # Which AI signal triggered this
    reasoning = Column(Text, nullable=True)              # Full verification report
    created_at = Column(DateTime, default=datetime.now)  # When trade was opened
    closed_at = Column(DateTime, nullable=True)          # When trade was closed


# ═══════════════════════════════════════════════════════════════════════
#  TABLE CREATION
#  (Run this file directly to create/upgrade all tables)
#  
#  IMPORTANT:
#    create_all() only creates tables that DON'T exist yet.
#    It will NOT modify existing tables. To reset everything,
#    use fix_db.py which drops and recreates all tables.
# ═══════════════════════════════════════════════════════════════════════
if __name__ == "__main__":
    print("--- 🛠️ UPGRADING DATABASE TABLES ---")
    Base.metadata.create_all(bind=engine)
    print("✅ All tables ready: users, accounts, prices, news_articles, trade_signals, portfolio_assets, trades")